## Importing the Libraries


In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot
import tensorflow as tf

In [6]:
tf.__version__

'2.7.0'

# Data Preprocessing


In [12]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values

In [13]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [14]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

## Encoding the Categorical Data

In [15]:
# In this we have the country and the gender of the customer
# Which means we need to incode the Categorical Data

In [19]:
# Label encoding the Gender
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [20]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [22]:
# Encoding the Geography columns

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [23]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [24]:
# We have now switched our categorical numbers to actual numbers

## Splitting the dataset into the Training and Test Set

In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

##  Feature Scalling

In [27]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [28]:
X_train

array([[-0.99850112,  1.71490137, -0.57273139, ..., -1.55337352,
         0.97725852,  0.42739449],
       [ 1.00150113, -0.58312392, -0.57273139, ..., -1.55337352,
        -1.02327069, -1.02548708],
       [-0.99850112,  1.71490137, -0.57273139, ...,  0.64376017,
         0.97725852, -0.94479772],
       ...,
       [ 1.00150113, -0.58312392, -0.57273139, ...,  0.64376017,
         0.97725852, -0.14096853],
       [ 1.00150113, -0.58312392, -0.57273139, ...,  0.64376017,
         0.97725852,  0.01781218],
       [-0.99850112,  1.71490137, -0.57273139, ...,  0.64376017,
        -1.02327069, -1.15822478]])

In [29]:
X_test

array([[ 1.00150113, -0.58312392, -0.57273139, ...,  0.64376017,
         0.97725852, -0.05360571],
       [ 1.00150113, -0.58312392, -0.57273139, ...,  0.64376017,
        -1.02327069, -0.58392685],
       [ 1.00150113, -0.58312392, -0.57273139, ..., -1.55337352,
         0.97725852, -0.16685331],
       ...,
       [-0.99850112, -0.58312392,  1.74601919, ..., -1.55337352,
         0.97725852,  1.0669965 ],
       [-0.99850112,  1.71490137, -0.57273139, ...,  0.64376017,
         0.97725852,  1.13101314],
       [-0.99850112,  1.71490137, -0.57273139, ...,  0.64376017,
         0.97725852, -0.88790165]])

## Building the Aritificial Neural Network

### Initializing the ANN

In [44]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer


In [45]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

### Adding the second Hidden layer

In [46]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

### Adding the ouput layer

In [47]:
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

## Training the ANN

In [48]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy' , metrics = ['accuracy'])

In [49]:
ann.fit(X_train,y_train,batch_size =  32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 3ms/step - loss: 0.5623 - accuracy: 0.7910
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4701 - accuracy: 0.7972
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4354 - accuracy: 0.7995
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4173 - accuracy: 0.8064
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4026 - accuracy: 0.8108
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3902 - accuracy: 0.8160
Epoch 7/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3807 - accuracy: 0.8176
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3740 - accuracy: 0.8204
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3689 - accuracy: 0.8255
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3639 - accura

250/250 [==============================] - 0s 1ms/step - loss: 0.3310 - accuracy: 0.8645
Epoch 82/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3307 - accuracy: 0.8639
Epoch 83/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3310 - accuracy: 0.8650
Epoch 84/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3306 - accuracy: 0.8641
Epoch 85/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3308 - accuracy: 0.8627
Epoch 86/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3306 - accuracy: 0.8639
Epoch 87/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3307 - accuracy: 0.8634
Epoch 88/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3301 - accuracy: 0.8640
Epoch 89/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3307 - accuracy: 0.8630
Epoch 90/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3306 - accuracy: 

## Predicting and Evaluating my Model 

### Predicting the result of a single Observation 

In [57]:
# Predicting on a random customer and had to change the scalling using sc.transform
print(ann.predict(sc.transform(np.array([[1, 0, 0, 200, 1, 40, 3, 60000, 2, 1, 1, 50000]])) ) > 0.5)

[[ True]]


In [64]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


## Confusion Matrix


In [65]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1540   45]
 [ 232  183]]


0.8615